name: Vitaliy Tuev
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: http://vetal232.github.io/
domain_name: 'http://vetal232.github.io/'
google_analytics: 'UA-XXXXXXXX-X'

github_username:  vetal232

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'

kramdown:
  auto_ids: true
  toc_levels: 1..6
# input: GFM
