name: stephanmax.is
author: Stephan Max
description: Blog, portfolio and digital playground of Stephan Max
established: 2013
url: http://stephanmax.is

source: src
destination: build

excerpt_separator: "\n\n"
permalink: /:categories/:title.html
highlighter: pygments

sass:
    sass_dir: assets/css
    style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: default
      category: writingabout
