# Site settings
title: Туев Виталий 
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  vetal232

# Build settings
markdown: kramdown

kramdown:
  auto_ids: true
  toc_levels: 1..6
# input: GFM
